[tool.poetry]
packages = [
	{ include = "brain_games" }
]
name = "hexlet-code"
version = "0.1.0"
description = ""
authors = ["Alex Subach <alex_28.02@mail.ru>"]
[tool.poetry.scripts]
brain-games = "brain_games.scripts.brain_games:main"
[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
